# Copyright (C) 2026 sonoransun — see LICENCE.txt


# binary target
#
BINARY = alpineModel


CONCURRENT=true

# required libs
#
USE_LIB_APP_UTILS = true


# target settings
#
INCLUDES =
LIBRARIES =

CPP_FILES = Connection.cpp \
            FuzzyDomain.cpp \
            Message.cpp \
            NetManager.cpp \
            PeerNode.cpp \
            alpineModel.cpp 



# build rules
#
include $(ALPINE_ROOT)/build/binary.mk


