# Copyright (C) 2026 sonoransun — see LICENCE.txt


DIRS = udp_socket_conn \
       map_test \
       dtcp_stack \
       spawn_process \
       sys_thread_test \
       auto_thread_test \
       corba_util_test \
       tcp_conn_test \


include $(ALPINE_ROOT)/build/recurse.mk
