# Copyright (C) 2026 sonoransun — see LICENCE.txt


# library target
#
LIBRARY = NetUtils


# required libs
#
CONCURRENT = true
USE_LIB_APP_UTILS = true


# target settings
#
INCLUDES =
LIBRARIES =

CPP_FILES = \
    NetUtils.cpp \
    UdpConnection.cpp \
    TcpAcceptor.cpp \
    TcpConnector.cpp \
    TcpAsyncConnector.cpp \
    TcpTransport.cpp \



# build rules
#
include $(ALPINE_ROOT)/build/library.mk

