# Copyright (C) 2026 sonoransun — see LICENCE.txt


# library target
#
LIBRARY = TransBase


# required libs
#
CONCURRENT        = true
USE_LIB_APP_UTILS = true


# target settings
#
INCLUDES = 
LIBRARIES =

CPP_FILES = \
    AcceptorInterface.cpp \
    ConnectorInterface.cpp \
    DataBlock.cpp \
    DataBuffer.cpp \
    MuxInterface.cpp \
    StackLinkInterface.cpp \
    TransportInterface.cpp \



# build rules
#
include $(ALPINE_ROOT)/build/library.mk

