# Copyright (C) 2026 sonoransun — see LICENCE.txt


# library target
#
LIBRARY = ConfigUtils


USE_LIB_THREAD_UTILS = true
USE_LIB_APP_UTILS = true


# target settings
#
INCLUDES = 
LIBRARIES =

CPP_FILES = \
    ArgumentMap.cpp \
    ConfigData.cpp \
    ConfigFile.cpp \
    Configuration.cpp \
    EnvironMap.cpp \



# build rules
#
include $(ALPINE_ROOT)/build/library.mk

