# Copyright (C) 2026 sonoransun — see LICENCE.txt


# library target
#
LIBRARY = SysUtils


# required libs
#
CONCURRENT            = true
USE_LIB_APP_UTILS     = true
USE_LIB_THREAD_UTILS  = true


# target settings
#
INCLUDES = 
LIBRARIES =

CPP_FILES = \
   DynamicLoader.cpp \
   FileUtils.cpp \
   SignalSet.cpp \
   SpawnProcess.cpp \
   UserUtils.cpp \



# build rules
#
include $(ALPINE_ROOT)/build/library.mk

