# Copyright (C) 2026 sonoransun — see LICENCE.txt


# library target
#
LIBRARY = CorbaUtils


# required libs
USE_CORBA   = true
USE_TAO_ORB = true
USE_LIB_APP_UTILS = true
USE_LIB_THREAD_UTILS = true



# target settings
#
INCLUDES = 
LIBRARIES =

CPP_FILES = \
    CosNamingUtils.cpp \
    OrbEventThread.cpp \
    OrbUtils.cpp \
    

# build rules
#
include $(ALPINE_ROOT)/build/library.mk

