# Copyright (C) 2026 sonoransun — see LICENCE.txt


# library target
#
LIBRARY = DtcpStackInterface


# required libs
#
USE_LIB_DTCP      = true
USE_LIB_APP_UTILS = true
USE_LIB_NET_UTILS = true


# target settings
#
INCLUDES = 
LIBRARIES =

CPP_FILES = \
    DtcpStackInterface.cpp \



# build rules
#
include $(ALPINE_ROOT)/build/library.mk

