# Copyright (C) 2026 sonoransun — see LICENCE.txt


# library target
#
LIBRARY = ThreadUtils


# required libs
#
CONCURRENT        = true
USE_LIB_APP_UTILS = true
USE_LIB_SYS_UTILS = true


# target settings
#
INCLUDES = 
LIBRARIES =

CPP_FILES = \
   AutoThread.cpp \
   SysThread.cpp \
   ReadWriteSem.cpp \
   ReadLock.cpp \
   WriteLock.cpp \
   Mutex.cpp \
   MutexLock.cpp \
   ThreadSigMask.cpp \
   ThreadUtils.cpp \



# build rules
#
include $(ALPINE_ROOT)/build/library.mk

