# Copyright (C) 2026 sonoransun — see LICENCE.txt


DIRS = Alpine \
       Freenet \
       Napster \
       SwarmCast \
       MojoNation \
       WebEngine \
       Publius \
       OceanStore \


include $(ALPINE_ROOT)/build/recurse.mk
