# Copyright (C) 2026 sonoransun — see LICENCE.txt


# library target
#
LIBRARY = DynTestLib


# required libs
#
CONCURRENT            = true
USE_LIB_APP_UTILS     = true
USE_LIB_SYS_UTILS     = true
USE_LIB_THREAD_UTILS  = true


# target settings
#
INCLUDES = 
LIBRARIES =

CPP_FILES = \
   DynamicObject.cpp \



# build rules
#
include $(ALPINE_ROOT)/build/library.mk

