# Copyright (C) 2026 sonoransun — see LICENCE.txt


# binary target
#
BINARY = udpSendTest


# required libs
#
USE_LIB_APP_UTILS = true
USE_LIB_NET_UTILS = true


# target settings
#
INCLUDES =
LIBRARIES =
CPP_FILES = udpSendTest.cpp



# build rules
#
include $(ALPINE_ROOT)/build/binary.mk

