# Copyright (C) 2026 sonoransun — see LICENCE.txt


# library target
#
LIBRARY = AlpineStackInterface


# required libs
#
CONCURRENT               = true
USE_LIB_ALPINE_PROTOCOL  = true
USE_LIB_APP_UTILS        = true
USE_LIB_NET_UTILS        = true
USE_LIB_CONFIG_UTILS     = true


# target settings
#
INCLUDES = 
LIBRARIES =

CPP_FILES = \
    AlpineStackInterface.cpp \



# build rules
#
include $(ALPINE_ROOT)/build/library.mk

