apiVersion: v1
kind: Service
metadata:
  name: alpine
  labels:
    app: alpine
spec:
  type: ClusterIP
  selector:
    app: alpine
  ports:
    - name: rest-api
      port: 8080
      targetPort: rest-api
    - name: beacon
      port: 8089
      targetPort: beacon
    - name: broadcast
      port: 8090
      targetPort: broadcast
    - name: protocol
      port: 9000
      targetPort: protocol
---
# Headless service for peer discovery
apiVersion: v1
kind: Service
metadata:
  name: alpine-headless
  labels:
    app: alpine
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: alpine
  ports:
    - name: protocol
      port: 9000
      targetPort: protocol
