# Copyright (C) 2026 sonoransun — see LICENCE.txt


# binary target
#
BINARY = threadTest


# required libs
#
USE_LIB_APP_UTILS    = true
USE_LIB_THREAD_UTILS = true


# target settings
#
INCLUDES = 
LIBRARIES = 
CPP_FILES = \
    TestThread.cpp \
    threadTest.cpp



# build rules
#
include $(ALPINE_ROOT)/build/binary.mk

