# Copyright (C) 2026 sonoransun — see LICENCE.txt


# library target
#
LIBRARY = ApplCore


# required libs
#
USE_LIB_APP_UTILS = true
USE_LIB_NET_UTILS = true
USE_LIB_THREAD_UTILS = true
USE_LIB_SYS_UTILS = true
USE_LIB_CONFIG_UTILS = true


# target settings
#
INCLUDES = 
LIBRARIES =

CPP_FILES = \
    ApplCore.cpp \
    SignalMonitorThread.cpp \



# build rules
#
include $(ALPINE_ROOT)/build/library.mk

