# Copyright (C) 2026 sonoransun — see LICENCE.txt


# required libs
#
USE_CORBA             = true
USE_TAO_ORB           = true
USE_LIB_APPLCORE      = true
USE_LIB_NET_UTILS     = true
USE_LIB_CONFIG_UTILS  = true
USE_LIB_SYS_UTILS     = true
USE_LIB_CORBA_UTILS   = true



# binary target
#
BINARY    = CorbaUtilsTest

INCLUDES  =
LIBRARIES = 

CPP_FILES = \
   CorbaUtilsTest.cpp \
   TestConfig.cpp \


# build rules
#
include $(ALPINE_ROOT)/build/binary.mk

