# Copyright (C) 2026 sonoransun — see LICENCE.txt


# binary target
#
BINARY = alpineTest


# required libs
#
USE_LIB_APP_UTILS = true
USE_LIB_NET_UTILS = true
USE_LIB_ALPINE_PROTOCOL = true


# target settings
#
INCLUDES  =
LIBRARIES =
CPP_FILES = alpineTest.cpp



# build rules
#
include $(ALPINE_ROOT)/build/binary.mk
