# Copyright (C) 2026 sonoransun — see LICENCE.txt



BINARY = dynamicLoaderTest


# required libs
#
USE_LIB_APP_UTILS      = true
USE_LIB_SYS_UTILS      = true
USE_LIB_THREAD_UTILS   = true
USE_LIB_APPLCORE       = true
USE_LIB_CONFIG_UTILS   = true



INCLUDES =  -I$(ALPINE_ROOT)/test/dl_test/DynLib
LIBRARIES =
CPP_FILES = dynamicLoaderTest.cpp



# build rules
#
include $(ALPINE_ROOT)/build/binary.mk

