# Copyright (C) 2026 sonoransun — see LICENCE.txt


# binary target
#

# required libs
#
USE_LIB_APPLCORE             = true
USE_CORBA                    = true
USE_TAO_ORB                  = true
USE_LIB_CORBA_SERVANT        = true
USE_LIB_CORBA_UTILS          = true
USE_LIB_ALPINE_CORBA_CLIENT  = true
USE_LIB_APP_UTILS            = true
USE_LIB_NET_UTILS            = true
USE_LIB_ALPINE_TRANSPORT     = true
USE_LIB_CONFIG_UTILS         = true



INCLUDES  =
LIBRARIES = 
BINARY    = AlpineCmdIf

CPP_FILES = \
   AlpineConfig.cpp \
   AlpineCmdIf.cpp \


# build rules
#
include $(ALPINE_ROOT)/build/binary.mk
