/// Copyright (C) 2026 sonoransun — see LICENCE.txt


#include <ShellCompletion.h>
#include <algorithm>
#include <format>
#include <sstream>


string
ShellCompletion::generateBash(const vector<pair<string, string>> & commands)
{
    std::ostringstream oss;

    // Sort commands for consistent output
    auto sorted = commands;
    std::sort(sorted.begin(), sorted.end());

    oss << "# Alpine CLI (alpc) — Bash completion\n"
        << "# Generated by AlpineCmdIf --completions bash\n"
        << "# Install: source <(AlpineCmdIf --completions bash)\n"
        << "#   or:    eval \"$(AlpineCmdIf --completions bash)\"\n\n"

        << "# Alias: 'alpc' -> AlpineCmdIf\n"
        << "alias alpc='AlpineCmdIf'\n\n"

        << "# Quick-action aliases (JSON, quiet, pipe-friendly)\n"
        << "alias alpc-peers='AlpineCmdIf --command getExtendedPeerList --json --quiet'\n"
        << "alias alpc-status='AlpineCmdIf --command getStatus --json --quiet'\n"
        << "alias alpc-query='AlpineCmdIf --command beginQuery --json --quiet'\n"
        << "alias alpc-results='AlpineCmdIf --command getQueryResults --json --quiet'\n"
        << "alias alpc-modules='AlpineCmdIf --command listActiveModules --json --quiet'\n"
        << "alias alpc-groups='AlpineCmdIf --command getUserGroupList --json --quiet'\n"
        << "alias alpc-interactive='AlpineCmdIf --command interactive'\n\n"

        << "# Table-formatted aliases\n"
        << "alias alpc-peers-t='AlpineCmdIf --command getExtendedPeerList --format table --quiet'\n"
        << "alias alpc-status-t='AlpineCmdIf --command getStatus --format table --quiet'\n"
        << "alias alpc-modules-t='AlpineCmdIf --command listActiveModules --format table --quiet'\n\n";

    // Build command list
    oss << "_alpc_completions() {\n"
        << "    local cur prev commands flags active_cmd i\n"
        << "    COMPREPLY=()\n"
        << "    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n"
        << "    prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n\n"
        << "    commands=\"";

    for (size_t i = 0; i < sorted.size(); ++i) {
        if (i > 0) {
            oss << " ";
        }
        oss << sorted[i].first;
    }

    oss << "\"\n\n"
        << "    flags=\"--serverAddress --serverPort --command --verbose --json --quiet "
           "--format --color --completions --logFile --logLevel --help --version\"\n\n"

        << "    # Find active --command value\n"
        << "    active_cmd=\"\"\n"
        << "    for ((i=1; i < COMP_CWORD; i++)); do\n"
        << "        if [[ \"${COMP_WORDS[i]}\" == \"--command\" && $((i+1)) -lt ${#COMP_WORDS[@]} ]]; then\n"
        << "            active_cmd=\"${COMP_WORDS[i+1]}\"\n"
        << "            break\n"
        << "        fi\n"
        << "    done\n\n"

        // Value completions for flags
        << "    case \"$prev\" in\n"
        << "        --command)\n"
        << "            COMPREPLY=( $(compgen -W \"$commands\" -- \"$cur\") )\n"
        << "            return 0;;\n"
        << "        --format)\n"
        << "            COMPREPLY=( $(compgen -W \"json table csv yaml\" -- \"$cur\") )\n"
        << "            return 0;;\n"
        << "        --completions)\n"
        << "            COMPREPLY=( $(compgen -W \"bash zsh\" -- \"$cur\") )\n"
        << "            return 0;;\n"
        << "        --serverAddress)\n"
        << "            COMPREPLY=( $(compgen -W \"localhost 127.0.0.1 ::1\" -- \"$cur\") )\n"
        << "            return 0;;\n"
        << "        --serverPort)\n"
        << "            COMPREPLY=( $(compgen -W \"8080 9000 8089\" -- \"$cur\") )\n"
        << "            return 0;;\n"
        << "        --logLevel)\n"
        << "            COMPREPLY=( $(compgen -W \"Silent Error Info Debug\" -- \"$cur\") )\n"
        << "            return 0;;\n"
        << "        --logFile|--modulePath)\n"
        << "            COMPREPLY=( $(compgen -f -- \"$cur\") )\n"
        << "            return 0;;\n"
        << "    esac\n\n"

        // Per-command argument completion
        << "    case \"$active_cmd\" in\n"
        << "        addDtcpPeer|getDtcpPeerId)\n"
        << "            [[ \"$cur\" == -* ]] && COMPREPLY=( $(compgen -W \"--ipAddress --port\" -- \"$cur\") )\n"
        << "            return 0;;\n"
        << "        getDtcpPeerStatus|activateDtcpPeer|deactivateDtcpPeer|pingDtcpPeer)\n"
        << "            [[ \"$cur\" == -* ]] && COMPREPLY=( $(compgen -W \"--peerId\" -- \"$cur\") )\n"
        << "            return 0;;\n"
        << "        excludeHost|allowHost)\n"
        << "            [[ \"$cur\" == -* ]] && COMPREPLY=( $(compgen -W \"--ipAddress\" -- \"$cur\") )\n"
        << "            return 0;;\n"
        << "        excludeSubnet|allowSubnet)\n"
        << "            [[ \"$cur\" == -* ]] && COMPREPLY=( $(compgen -W \"--subnetIpAddress --subnetMask\" -- \"$cur\") )\n"
        << "            return 0;;\n"
        << "        createUserGroup|destroyUserGroup)\n"
        << "            [[ \"$cur\" == -* ]] && COMPREPLY=( $(compgen -W \"--groupName\" -- \"$cur\") )\n"
        << "            return 0;;\n"
        << "        addPeerToGroup|removePeerFromGroup|getPeerUserGroupList)\n"
        << "            [[ \"$cur\" == -* ]] && COMPREPLY=( $(compgen -W \"--peerId --groupName\" -- \"$cur\") )\n"
        << "            return 0;;\n"
        << "        beginQuery)\n"
        << "            [[ \"$cur\" == -* ]] && COMPREPLY=( $(compgen -W \"--queryString --numHits --moduleId\" -- \"$cur\") )\n"
        << "            return 0;;\n"
        << "        getQueryStatus|pauseQuery|resumeQuery|cancelQuery|getQueryResults)\n"
        << "            [[ \"$cur\" == -* ]] && COMPREPLY=( $(compgen -W \"--queryId\" -- \"$cur\") )\n"
        << "            return 0;;\n"
        << "        registerModule|loadModule)\n"
        << "            [[ \"$cur\" == -* ]] && COMPREPLY=( $(compgen -W \"--moduleName --modulePath\" -- \"$cur\") )\n"
        << "            [[ \"$prev\" == \"--modulePath\" ]] && COMPREPLY=( $(compgen -f -X '!*.so' -- \"$cur\") )\n"
        << "            return 0;;\n"
        << "        unregisterModule|unloadModule|getModuleInfo)\n"
        << "            [[ \"$cur\" == -* ]] && COMPREPLY=( $(compgen -W \"--moduleId\" -- \"$cur\") )\n"
        << "            return 0;;\n"
        << "        help)\n"
        << "            COMPREPLY=( $(compgen -W \"$commands\" -- \"$cur\") )\n"
        << "            return 0;;\n"
        << "    esac\n\n"

        << "    if [[ \"$cur\" == -* ]]; then\n"
        << "        COMPREPLY=( $(compgen -W \"$flags\" -- \"$cur\") )\n"
        << "    else\n"
        << "        COMPREPLY=( $(compgen -W \"$commands\" -- \"$cur\") )\n"
        << "    fi\n"
        << "}\n\n"
        << "complete -o default -F _alpc_completions alpc\n"
        << "complete -o default -F _alpc_completions AlpineCmdIf\n";

    return oss.str();
}


string
ShellCompletion::generateZsh(const vector<pair<string, string>> & commands)
{
    std::ostringstream oss;

    // Sort commands for consistent output
    auto sorted = commands;
    std::sort(sorted.begin(), sorted.end());

    oss << "#compdef alpc AlpineCmdIf\n"
        << "# Alpine CLI (alpc) — Zsh completion\n"
        << "# Generated by AlpineCmdIf --completions zsh\n"
        << "# Install: cp to ~/.zsh/completions/_alpc\n\n"

        << "# Alias setup\n"
        << "alias alpc='AlpineCmdIf'\n"
        << "alias alpc-peers='AlpineCmdIf --command getExtendedPeerList --json --quiet'\n"
        << "alias alpc-status='AlpineCmdIf --command getStatus --json --quiet'\n"
        << "alias alpc-query='AlpineCmdIf --command beginQuery --json --quiet'\n"
        << "alias alpc-results='AlpineCmdIf --command getQueryResults --json --quiet'\n"
        << "alias alpc-modules='AlpineCmdIf --command listActiveModules --json --quiet'\n"
        << "alias alpc-groups='AlpineCmdIf --command getUserGroupList --json --quiet'\n"
        << "alias alpc-interactive='AlpineCmdIf --command interactive'\n"
        << "alias alpc-peers-t='AlpineCmdIf --command getExtendedPeerList --format table --quiet'\n"
        << "alias alpc-status-t='AlpineCmdIf --command getStatus --format table --quiet'\n\n";

    // Categorize commands
    oss << "_alpc() {\n"
        << "    local -a peer_cmds net_cmds group_cmds query_cmds mod_cmds sys_cmds\n\n"
        << "    peer_cmds=(\n";

    // Emit categorized command lists
    auto emitCmd = [&](const string & name, const string & desc) {
        string escaped = desc;
        for (size_t pos = 0; (pos = escaped.find(':', pos)) != string::npos; pos += 2) {
            escaped.insert(pos, "\\");
        }
        oss << "        '" << name << ":" << escaped << "'\n";
    };

    // Map commands to categories
    for (const auto & [name, desc] : sorted) {
        if (name.contains("Dtcp"s) || name.contains("Peer"s) || name == "getExtendedPeerList"s) {
            // peer category — handled below
        }
    }

    // Just emit all in sorted order with category separation
    oss << "    )\n\n";

    // Use a single commands array for simplicity in the generated script
    oss << "    local -a commands\n"
        << "    commands=(\n";

    for (const auto & [name, desc] : sorted) {
        string escaped = desc;
        for (size_t pos = 0; (pos = escaped.find(':', pos)) != string::npos; pos += 2) {
            escaped.insert(pos, "\\");
        }
        oss << "        '" << name << ":" << escaped << "'\n";
    }

    oss << "    )\n\n"

        << "    # Find active --command\n"
        << "    local active_cmd=\"\" i\n"
        << "    for ((i=1; i < $CURRENT; i++)); do\n"
        << "        if [[ \"${words[i]}\" == \"--command\" && $((i+1)) -le ${#words} ]]; then\n"
        << "            active_cmd=\"${words[i+1]}\"\n"
        << "            break\n"
        << "        fi\n"
        << "    done\n\n"

        // Per-command argument completion
        << "    case \"$active_cmd\" in\n"
        << "        addDtcpPeer|getDtcpPeerId)\n"
        << "            _arguments -s '--ipAddress[IP address]:addr:' '--port[Port]:port:' '*:' && return;;\n"
        << "        getDtcpPeerStatus|activateDtcpPeer|deactivateDtcpPeer|pingDtcpPeer)\n"
        << "            _arguments -s '--peerId[Peer ID]:id:' '*:' && return;;\n"
        << "        excludeHost|allowHost)\n"
        << "            _arguments -s '--ipAddress[IP address]:addr:' '*:' && return;;\n"
        << "        excludeSubnet|allowSubnet)\n"
        << "            _arguments -s '--subnetIpAddress[Subnet IP]:addr:' '--subnetMask[Mask]:mask:' '*:' && return;;\n"
        << "        createUserGroup|destroyUserGroup)\n"
        << "            _arguments -s '--groupName[Group name]:name:' '*:' && return;;\n"
        << "        addPeerToGroup|removePeerFromGroup|getPeerUserGroupList)\n"
        << "            _arguments -s '--peerId[Peer ID]:id:' '--groupName[Group]:name:' '*:' && return;;\n"
        << "        beginQuery)\n"
        << "            _arguments -s '--queryString[Search query]:query:' '--numHits[Max results]:n:' '--moduleId[Module]:id:' '*:' && return;;\n"
        << "        getQueryStatus|pauseQuery|resumeQuery|cancelQuery|getQueryResults)\n"
        << "            _arguments -s '--queryId[Query ID]:id:' '*:' && return;;\n"
        << "        registerModule|loadModule)\n"
        << "            _arguments -s '--moduleName[Name]:name:' '--modulePath[Path]:path:_files -g \"*.so *.dll *.dylib\"' '*:' && return;;\n"
        << "        unregisterModule|unloadModule|getModuleInfo)\n"
        << "            _arguments -s '--moduleId[Module ID]:id:' '*:' && return;;\n"
        << "        help)\n"
        << "            _describe 'command' commands && return;;\n"
        << "    esac\n\n"

        // Global args
        << "    _arguments -s \\\n"
        << "        '--serverAddress[Server address]:addr:(localhost 127.0.0.1 \\:\\:1)' \\\n"
        << "        '--serverPort[Server port]:port:(8080 9000 8089)' \\\n"
        << "        '--command[Command]:cmd:->cmd' \\\n"
        << "        '--verbose[Verbose output]' \\\n"
        << "        '--json[JSON output]' \\\n"
        << "        '--quiet[Quiet mode]' \\\n"
        << "        '--format[Output format]:fmt:(json table csv yaml)' \\\n"
        << "        '--color[Color output]' \\\n"
        << "        '--completions[Shell completions]:sh:(bash zsh)' \\\n"
        << "        '--logFile[Log file]:file:_files' \\\n"
        << "        '--logLevel[Log level]:level:(Silent Error Info Debug)' \\\n"
        << "        '--help[Show help]' \\\n"
        << "        '--version[Show version]'\n\n"

        << "    case $state in\n"
        << "        cmd) _describe 'command' commands;;\n"
        << "    esac\n"
        << "}\n\n"
        << "_alpc \"$@\"\n";

    return oss.str();
}
