// generated 2001/2/26 23:18:05 CST by root@logic.
// using glademm V0.5_11
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /projects/alpine/gui/glade-proj/EasyClient/alpine.glade
// for gtk 1.2.8 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in ./src/MainWindow.cc

#include "MainWindow.hh"

MainWindow_Glade::MainWindow_Glade(
) : Gtk::Window(GTK_WINDOW_TOPLEVEL)
{   mainwindow = this;
   menu_exit = new Gtk::MenuItem("Exit");
   menu_file_menu = new Gtk::Menu();
   menu_file = new Gtk::MenuItem("File");
   menu_preferences = new Gtk::MenuItem("Preferences");
   menu_settings_menu = new Gtk::Menu();
   menu_settings = new Gtk::MenuItem("Settings");
   menu_about = new Gtk::MenuItem("About");
   menu_users_guide = new Gtk::MenuItem("Users Guide");
   menu_help_menu = new Gtk::Menu();
   menu_help = new Gtk::MenuItem("Help");
   mainmenu = new Gtk::MenuBar();
   mainnotebook = new MainNotebook();
   statusbar = new StatusBar();
   vbox3 = new Gtk::VBox(false, 0);
   menu_exit->set_name("menu_exit");
   menu_file_menu->set_name("menu_file_menu");
   menu_file_menu->append(*menu_exit);
   menu_file->set_name("menu_file");
   menu_file->set_submenu(*menu_file_menu);
   menu_preferences->set_name("menu_preferences");
   menu_settings_menu->set_name("menu_settings_menu");
   menu_settings_menu->append(*menu_preferences);
   menu_settings->set_name("menu_settings");
   menu_settings->set_submenu(*menu_settings_menu);
   menu_about->set_name("menu_about");
   menu_users_guide->set_name("menu_users_guide");
   menu_help_menu->set_name("menu_help_menu");
   menu_help_menu->append(*menu_about);
   menu_help_menu->append(*menu_users_guide);
   menu_help->set_name("menu_help");
   menu_help->set_submenu(*menu_help_menu);
   mainmenu->set_name("MainMenu");
   mainmenu->set_border_width(2);
   mainmenu->append(*menu_file);
   mainmenu->append(*menu_settings);
   mainmenu->append(*menu_help);
   vbox3->set_name("vbox3");
   vbox3->pack_start(*mainmenu, false, false, 0);
   vbox3->pack_start(*mainnotebook);
   vbox3->pack_start(*statusbar, false, false, 0);
   mainwindow->set_usize(700, 620);
   mainwindow->set_name("MainWindow");
   mainwindow->set_title("ALPINE Network Client");
   mainwindow->set_position(GTK_WIN_POS_CENTER);
   mainwindow->set_policy(true, true, false);
   mainwindow->add(*vbox3);
   menu_exit->show();
   menu_file_menu->show();
   menu_file->show();
   menu_preferences->show();
   menu_settings_menu->show();
   menu_settings->show();
   menu_about->show();
   menu_users_guide->show();
   menu_help_menu->show();
   menu_help->show();
   mainmenu->show();
   vbox3->show();
   mainwindow->show();
}

MainWindow_Glade::~MainWindow_Glade()
{   delete menu_exit;
   delete menu_file_menu;
   delete menu_file;
   delete menu_preferences;
   delete menu_settings_menu;
   delete menu_settings;
   delete menu_about;
   delete menu_users_guide;
   delete menu_help_menu;
   delete menu_help;
   delete mainmenu;
   delete mainnotebook;
   delete statusbar;
   delete vbox3;
}
