// generated 2001/2/26 23:18:05 CST by root@logic.
// using glademm V0.5_11
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /projects/alpine/gui/glade-proj/EasyClient/alpine.glade
// for gtk 1.2.8 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in ./src/MainNotebook.hh and./src/MainNotebook.cc

#ifndef _MAINNOTEBOOK_GLADE_HH
#  define _MAINNOTEBOOK_GLADE_HH

#include <gtk--/notebook.h>
#include <gtk--/label.h>
#include <gtk--/entry.h>
#include <gtk--/button.h>
#include <gtk--/box.h>
#include <gtk--/separator.h>
#include <gtk--/clist.h>
#include <gtk--/scrolledwindow.h>
#include <gtk--/alignment.h>
#include <gtk--/frame.h>
#include <gtk--/combo.h>
#include <gtk--/spinbutton.h>
#include <gtk--/adjustment.h>
#include <gtk--/text.h>
#include <gtk--/checkbutton.h>

class MainNotebook_Glade : public Gtk::Notebook
{   
        
        Gtk::Notebook *mainnotebook;
        Gtk::Label *label14;
        Gtk::Entry *searchentry;
        Gtk::Label *label113;
        Gtk::Button *button19;
        Gtk::HBox *hbox2;
        Gtk::HSeparator *hseparator16;
        Gtk::Label *label16;
        Gtk::HSeparator *hseparator3;
        Gtk::CList *clist2;
        Gtk::ScrolledWindow *scrolledwindow1;
        Gtk::VBox *vbox5;
        Gtk::Alignment *alignment5;
        Gtk::HSeparator *hseparator4;
        Gtk::Alignment *alignment6;
        Gtk::Label *label20;
        Gtk::Label *label21;
        Gtk::Label *totalmatcheslabel;
        Gtk::Label *label114;
        Gtk::Button *button2;
        Gtk::HBox *hbox3;
        Gtk::Alignment *alignment7;
        Gtk::VBox *vbox6;
        Gtk::HSeparator *hseparator23;
        Gtk::Alignment *alignment8;
        Gtk::VBox *vbox4;
        Gtk::Frame *frame1;
        Gtk::Label *searchtab;
        Gtk::Label *label32;
        Gtk::Combo *filetypefilterlist;
        Gtk::Label *label115;
        Gtk::Label *label33;
        Gtk::Combo *peerfilterlist;
        Gtk::HBox *hbox4;
        Gtk::Frame *frame2;
        Gtk::Alignment *alignment9;
        Gtk::CList *clist3;
        Gtk::ScrolledWindow *scrolledwindow2;
        Gtk::HSeparator *hseparator6;
        Gtk::Alignment *alignment10;
        Gtk::Label *label117;
        Gtk::Label *label116;
        Gtk::Button *canceldownloadbutton;
        Gtk::HBox *hbox5;
        Gtk::Alignment *alignment11;
        Gtk::VBox *vbox8;
        Gtk::Frame *frame3;
        Gtk::CList *clist4;
        Gtk::ScrolledWindow *scrolledwindow3;
        Gtk::HSeparator *hseparator7;
        Gtk::Label *label48;
        Gtk::Combo *combo4;
        Gtk::Button *feedbackbutton;
        Gtk::HBox *hbox6;
        Gtk::Alignment *alignment12;
        Gtk::VBox *vbox9;
        Gtk::Frame *frame4;
        Gtk::VBox *vbox7;
        Gtk::Label *downloadtab;
        Gtk::Label *label53;
        Gtk::SpinButton *maxuploadsentryspinner;
        Gtk::Adjustment *maxuploadsentryspinner_adj;
        Gtk::Label *label118;
        Gtk::Label *label54;
        Gtk::SpinButton *maxuseruploadsentryspinner;
        Gtk::Adjustment *maxuseruploadsentryspinner_adj;
        Gtk::Label *label132;
        Gtk::HBox *hbox8;
        Gtk::Frame *frame5;
        Gtk::CList *clist5;
        Gtk::ScrolledWindow *scrolledwindow4;
        Gtk::HSeparator *hseparator8;
        Gtk::Alignment *alignment13;
        Gtk::Button *button3;
        Gtk::HBox *hbox9;
        Gtk::Alignment *alignment14;
        Gtk::VBox *vbox18;
        Gtk::Frame *frame6;
        Gtk::VBox *vbox10;
        Gtk::Label *uploadstab;
        Gtk::Label *label59;
        Gtk::Entry *entry4;
        Gtk::Label *label119;
        Gtk::Label *label129;
        Gtk::SpinButton *spinbutton12;
        Gtk::Adjustment *spinbutton12_adj;
        Gtk::Label *label130;
        Gtk::Label *label60;
        Gtk::Entry *entry5;
        Gtk::Label *label131;
        Gtk::Button *button26;
        Gtk::HBox *hbox10;
        Gtk::Alignment *alignment15;
        Gtk::HSeparator *hseparator22;
        Gtk::Label *label133;
        Gtk::Entry *entry9;
        Gtk::Button *importpeerlist;
        Gtk::HBox *hbox29;
        Gtk::VBox *vbox19;
        Gtk::Frame *frame7;
        Gtk::CList *clist7;
        Gtk::ScrolledWindow *scrolledwindow5;
        Gtk::HSeparator *hseparator9;
        Gtk::Button *button4;
        Gtk::Button *button5;
        Gtk::Button *button6;
        Gtk::HBox *hbox11;
        Gtk::Alignment *alignment16;
        Gtk::VBox *vbox20;
        Gtk::Frame *frame8;
        Gtk::CList *clist8;
        Gtk::ScrolledWindow *scrolledwindow6;
        Gtk::HSeparator *hseparator10;
        Gtk::Button *button7;
        Gtk::Button *button8;
        Gtk::Button *button9;
        Gtk::HBox *hbox12;
        Gtk::Alignment *alignment17;
        Gtk::VBox *vbox21;
        Gtk::Frame *frame9;
        Gtk::VBox *vbox11;
        Gtk::Label *peerstab;
        Gtk::Label *label85;
        Gtk::HBox *hbox17;
        Gtk::HSeparator *hseparator13;
        Gtk::Label *label86;
        Gtk::Entry *entry8;
        Gtk::Label *label121;
        Gtk::HBox *hbox18;
        Gtk::VBox *vbox25;
        Gtk::Frame *frame14;
        Gtk::Text *text1;
        Gtk::ScrolledWindow *scrolledwindow9;
        Gtk::Frame *frame15;
        Gtk::HSeparator *hseparator14;
        Gtk::Button *button14;
        Gtk::Label *label122;
        Gtk::Button *button15;
        Gtk::HBox *hbox20;
        Gtk::VBox *vbox26;
        Gtk::VBox *vbox23;
        Gtk::Frame *frame11;
        Gtk::CList *clist11;
        Gtk::ScrolledWindow *scrolledwindow10;
        Gtk::HSeparator *hseparator15;
        Gtk::Button *button16;
        Gtk::Button *button17;
        Gtk::Button *button18;
        Gtk::HBox *hbox21;
        Gtk::Alignment *alignment19;
        Gtk::VBox *vbox27;
        Gtk::Frame *frame16;
        Gtk::VBox *vbox13;
        Gtk::Label *sharingtab;
        Gtk::Label *label97;
        Gtk::Combo *combo5;
        Gtk::Label *label123;
        Gtk::CheckButton *checkbutton1;
        Gtk::HBox *hbox26;
        Gtk::Alignment *alignment22;
        Gtk::HSeparator *hseparator19;
        Gtk::Label *label98;
        Gtk::SpinButton *spinbutton9;
        Gtk::Adjustment *spinbutton9_adj;
        Gtk::Label *label124;
        Gtk::Label *label99;
        Gtk::Combo *combo6;
        Gtk::Label *label125;
        Gtk::HBox *hbox27;
        Gtk::Alignment *alignment23;
        Gtk::VBox *vbox31;
        Gtk::Frame *frame21;
        Gtk::CList *clist13;
        Gtk::ScrolledWindow *scrolledwindow12;
        Gtk::HSeparator *hseparator20;
        Gtk::Button *button24;
        Gtk::Label *label126;
        Gtk::Button *button23;
        Gtk::HBox *hbox28;
        Gtk::Alignment *alignment24;
        Gtk::VBox *vbox33;
        Gtk::Frame *frame23;
        Gtk::HSeparator *hseparator21;
        Gtk::VBox *vbox29;
        Gtk::Frame *frame19;
        Gtk::VBox *vbox15;
        Gtk::Label *netoptionstab;
protected:
        
        MainNotebook_Glade();
        
        ~MainNotebook_Glade();
};
#endif
