// generated 2001/2/26 23:18:05 CST by root@logic.
// using glademm V0.5_11
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /projects/alpine/gui/glade-proj/EasyClient/alpine.glade
// for gtk 1.2.8 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in ./src/StatusBar.hh and./src/StatusBar.cc

#ifndef _STATUSBAR_GLADE_HH
#  define _STATUSBAR_GLADE_HH

#include <gtk--/statusbar.h>

class StatusBar_Glade : public Gtk::Statusbar
{   
        
        Gtk::Statusbar *statusbar;
protected:
        
        StatusBar_Glade();
        
        ~StatusBar_Glade();
};
#endif
