// generated 2001/2/26 23:18:05 CST by root@logic.
// using glademm V0.5_11
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /projects/alpine/gui/glade-proj/EasyClient/alpine.glade
// for gtk 1.2.8 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in ./src/StatusBar.cc

#include "StatusBar.hh"

StatusBar_Glade::StatusBar_Glade(
)
{   statusbar = this;
   statusbar->set_name("StatusBar");
   statusbar->show();
}

StatusBar_Glade::~StatusBar_Glade()
{   
}
