# Copyright (C) 2026 sonoransun — see LICENCE.txt


# library target
#
LIBRARY = AlpineIdl


# required libs
CONCURRENT = true
USE_CORBA   = true
USE_TAO_ORB = true
#USE_ORBIT_ORB = true


# target settings
#
INCLUDES = 
LIBRARIES =

IDL_FILES = \
   Alpine.idl \


# build rules
#
include $(ALPINE_ROOT)/build/library.mk

