// generated 2001/2/26 23:12:28 CST by root@logic.
// using glademm V0.5_11
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /projects/alpine/gui/glade-proj/ExpertClient/alpine.glade
// for gtk 1.2.8 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in ./src/MainWindow.hh and./src/MainWindow.cc

#ifndef _MAINWINDOW_GLADE_HH
#  define _MAINWINDOW_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/accelgroup.h>
#include <gtk--/list.h>
#include <gtk--/menu.h>
#include <gtk--/menubar.h>
#include "MainNotebook.hh"
#include <gtk--/statusbar.h>
#include <gtk--/box.h>

class MainWindow_Glade : public Gtk::Window
{   
        
        Gtk::Window *mainwindow;
        Gtk::MenuItem *menu_exit;
        Gtk::Menu *menu_file_menu;
        Gtk::MenuItem *menu_file;
        Gtk::MenuItem *menu_preferences;
        Gtk::Menu *menu_settings_menu;
        Gtk::MenuItem *menu_settings;
        Gtk::MenuItem *menu_about;
        Gtk::MenuItem *menu_users_guide;
        Gtk::Menu *menu_help_menu;
        Gtk::MenuItem *menu_help;
        Gtk::MenuBar *mainmenu;
        MainNotebook *mainnotebook;
        Gtk::Statusbar *statusbar;
        Gtk::VBox *vbox3;
protected:
        
        MainWindow_Glade();
        
        ~MainWindow_Glade();
};
#endif
