# Copyright (C) 2026 sonoransun — see LICENCE.txt


# library target
#
LIBRARY = CorbaAdmin


# required libs
USE_CORBA                    = true
USE_TAO_ORB                  = true
USE_LIB_CORBA_UTILS          = true
USE_LIB_ALPINE_CORBA_SERVER  = true
USE_LIB_APP_UTILS            = true
USE_LIB_THREAD_UTILS         = true



# target settings
#
INCLUDES = 
LIBRARIES =

CPP_FILES = \
    CorbaAdmin.cpp \
    

# build rules
#
include $(ALPINE_ROOT)/build/library.mk

