#//////
#//
#//  Copyright (C) 2000                           Martin R. Peck
#//                                               coderman@mindspring.com
#//
#//  This program is free software; you can redistribute it and/or modify
#//  it under the terms of the GNU General Public License as published by
#//  the Free  Software Foundation;  either version 2  of the License, or
#//  (at your option) any later version.
#//
#//  This program is distributed in the hope that it will be useful,  but
#//  WITHOUT  ANY  WARRANTY.   This also includes any implied warranty of
#//  MERCHANTABILITY  or  FITNESS FOR A PARTICULAR PURPOSE.   See the GNU
#//  General Public License for more details.
#//
#//  You should  have received  a copy of  the GNU General Public License
#//  along with this program; if not, please write:
#//
#//      Free Software Foundation, Inc.
#//      59 Temple Place, Suite 330
#//      Boston, MA  02111-1307  USA
#//
#//  An online version is available at the following locations:
#//      http://www.gnu.org/copyleft/gpl.html
#//      http://CubicMeterCrystal.com/meta/info/gnu_license.html
#//
#//////


DIRS = \
   EasyClient \
   ExpertClient \


include $(ALPINE_ROOT)/build/recurse.mk

