# Copyright (C) 2026 sonoransun — see LICENCE.txt


# binary target
#
BINARY = mapTest


# required libs
#
CONCURRENT = true
USE_LIB_APP_UTILS = true


# target settings
#
INCLUDES = 
LIBRARIES = 
CPP_FILES = mapTest.cpp



# build rules
#
include $(ALPINE_ROOT)/build/binary.mk
