# Copyright (C) 2026 sonoransun — see LICENCE.txt


# binary target
#
BINARY = spawnProcess


# required libs
#
USE_LIB_APP_UTILS = true
USE_LIB_SYS_UTILS = true
USE_LIB_THREAD_UTILS = true


# target settings
#
INCLUDES =
LIBRARIES =
CPP_FILES = spawnProcess.cpp



# build rules
#
include $(ALPINE_ROOT)/build/binary.mk
