#//////
#//
#//  Copyright (C) 2026  sonoransun
#//
#//  Permission is hereby granted, free of charge, to any person obtaining a copy
#//  of this software and associated documentation files (the "Software"), to deal
#//  in the Software without restriction, including without limitation the rights
#//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#//  copies of the Software, and to permit persons to whom the Software is
#//  furnished to do so, subject to the following conditions:
#//
#//  The above copyright notice and this permission notice shall be included in all
#//  copies or substantial portions of the Software.
#//
#//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#//  SOFTWARE.
#//
#//////


# library target
#
LIBRARY = AlpineProtocol


# required libs
#
USE_LIB_DTCP              = true
USE_LIB_ALPINE_TRANSPORT  = true
USE_LIB_APP_UTILS         = true
USE_LIB_NET_UTILS         = true
USE_LIB_THREAD_UTILS      = true
USE_LIB_CONFIG_UTILS      = true
USE_LIB_TRANS_BASE        = true


# target settings
#
INCLUDES = 
LIBRARIES =

CPP_FILES = \
    AlpineBaseOptionData.cpp \
    AlpineBroadcast.cpp \
    AlpineExtensionIndex.cpp \
    AlpineGroup.cpp \
    AlpineGroupMgr.cpp \
    AlpineModuleMgr.cpp \
    AlpinePacket.cpp \
    AlpinePeerLocation.cpp \
    AlpinePeerMgr.cpp \
    AlpinePeerOptionData.cpp \
    AlpinePeerPacket.cpp \
    AlpinePeerProfile.cpp \
    AlpinePeerProfileIndex.cpp \
    AlpineProtocol.cpp \
    AlpineProxyOptionData.cpp \
    AlpineProxyPacket.cpp \
    AlpineQuery.cpp \
    AlpineQueryMgr.cpp \
    AlpineQueryModuleIndex.cpp \
    AlpineQueryOptionData.cpp \
    AlpineQueryOptions.cpp \
    AlpineQueryPacket.cpp \
    AlpineQueryRequest.cpp \
    AlpineQueryResults.cpp \
    AlpineQueryStatus.cpp \
    AlpineRatingEngine.cpp \
    AlpineResourceDesc.cpp \
    AlpineResourceDescSet.cpp \
    AlpineServiceThread.cpp \
    AlpineStack.cpp \
    AlpineStackConfig.cpp \



# build rules
#
include $(ALPINE_ROOT)/build/library.mk

