# Copyright (C) 2026 sonoransun — see LICENCE.txt


# library target
#
LIBRARY = AlpineProtocol


# required libs
#
USE_LIB_DTCP              = true
USE_LIB_ALPINE_TRANSPORT  = true
USE_LIB_APP_UTILS         = true
USE_LIB_NET_UTILS         = true
USE_LIB_THREAD_UTILS      = true
USE_LIB_CONFIG_UTILS      = true
USE_LIB_TRANS_BASE        = true


# target settings
#
INCLUDES = 
LIBRARIES =

CPP_FILES = \
    AlpineBaseOptionData.cpp \
    AlpineBroadcast.cpp \
    AlpineExtensionIndex.cpp \
    AlpineGroup.cpp \
    AlpineGroupMgr.cpp \
    AlpineModuleMgr.cpp \
    AlpinePacket.cpp \
    AlpinePeerLocation.cpp \
    AlpinePeerMgr.cpp \
    AlpinePeerOptionData.cpp \
    AlpinePeerPacket.cpp \
    AlpinePeerProfile.cpp \
    AlpinePeerProfileIndex.cpp \
    AlpineProtocol.cpp \
    AlpineProxyOptionData.cpp \
    AlpineProxyPacket.cpp \
    AlpineQuery.cpp \
    AlpineQueryMgr.cpp \
    AlpineQueryModuleIndex.cpp \
    AlpineQueryOptionData.cpp \
    AlpineQueryOptions.cpp \
    AlpineQueryPacket.cpp \
    AlpineQueryRequest.cpp \
    AlpineQueryResults.cpp \
    AlpineQueryStatus.cpp \
    AlpineRatingEngine.cpp \
    AlpineResourceDesc.cpp \
    AlpineResourceDescSet.cpp \
    AlpineServiceThread.cpp \
    AlpineStack.cpp \
    AlpineStackConfig.cpp \



# build rules
#
include $(ALPINE_ROOT)/build/library.mk

